export const subjectOptions = [
    { value: '', label: 'Chọn môn học' },
    { value: '1', label: 'Toán' },
    { value: '2', label: 'Vật lí' },
    { value: '3', label: 'Hóa học' },
    { value: '4', label: 'Sinh học' },
    { value: '5', label: 'Ngữ văn' },
    { value: '6', label: 'Tiếng Việt' },
    { value: '7', label: 'Lịch sử' },
    { value: '8', label: 'Địa lí' },
    { value: '9', label: 'Tiếng Anh' },
    { value: '10', label: 'Giáo dục công dân (GDCD)' },
    { value: '11', label: 'Đạo đức' },
    { value: '12', label: 'Giáo dục kinh tế và pháp luật' },
    { value: '13', label: 'Giáo dục Quốc phòng và An ninh' },
    { value: '14', label: 'Tự nhiên và Xã hội' },
    { value: '15', label: 'Khoa học' },
    { value: '16', label: 'Khoa học tự nhiên' },
    { value: '17', label: 'Lịch sử và Địa lí' },
    { value: '18', label: 'Tin học' },
    { value: '19', label: 'Công nghệ' },
    { value: '20', label: 'Âm nhạc' },
    { value: '21', label: 'Mĩ thuật' },
    { value: '22', label: 'Giáo dục thể chất' },
    { value: '23', label: 'Hoạt động trải nghiệm, hướng nghiệp' },
    { value: '24', label: 'Luyện viết chữ đẹp' },
    { value: '25', label: 'Tiếng Anh giao tiếp' },
    { value: '26', label: 'Luyện thi IELTS' },
    { value: '27', label: 'Luyện thi TOEIC' },
    { value: '28', label: 'Lập trình' },
    { value: '29', label: 'Tiếng Pháp' },
    { value: '30', label: 'Tiếng Nhật' },
    { value: '31', label: 'Tiếng Trung' },
    { value: '32', label: 'Tiếng Hàn' },
    { value: '33', label: 'Tiếng Đức' },
];